name: build and deploy

on:
  push:
    branches:
      - main

jobs:
  build-page-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1

      - run: yarn install

      - run: yarn build

      - name: commit & push
        env: # Or as an environment variable
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NAME: ${{ secrets.NAME }}
          EMAIL: ${{ secrets.EMAIL }}
        run: |
          git add -N . # 新規ファイルを含める
          if ! git diff --exit-code --quiet
          then
            git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com//***/introduction-2-computer-graphics
            git config --global user.name "${NAME}"
            git config --global user.email "${EMAIL}"
            git add --update
            git commit -m "auto update from github actions."
            git pull origin main
            git push origin main
          fi