name: build and deploy

on:
  push:
    branches:
      - deploy

jobs:
  build-page-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1

      - run: yarn install

      - run: yarn build

      - name: commit & push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NAME: ${{ secrets.NAME }}
          EMAIL: ${{ secrets.EMAIL }}
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/DaichiTakigawa/introduction-2-computer-graphics
          git config --global user.name "${NAME}"
          git config --global user.email "${EMAIL}"
          git config --global pull.rebase false
          echo "before checkout"
          ls -la
          git pull origin main
          git checkout main
          echo "after checkout"
          ls -la
          cp -r docs/* .
          rm -r docs
          echo "after cp"
          ls -la
          git add .
          if ! git diff --cached --exit-code --quiet; then
            git add --update
            git commit -m "Automated deployment: $(date -u)"
            git push origin  HEAD:main
          fi